#ifndef __MyProject2MyFrame1__
#define __MyProject2MyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "MyProjectBase.h"

#include "BG_ICMP.h"

//// end generated include

/** Implementing MyFrame1 */
class MyProject2MyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_BN_LoadHostListOnButtonClick( wxCommandEvent& event );
		void m_BN_RunOnceOnButtonClick( wxCommandEvent& event );
		void m_BN_RunPeriodicOnButtonClick( wxCommandEvent& event );
	public:
		/** Constructor */
		MyProject2MyFrame1( wxWindow* parent );
	//// end generated class members

		~MyProject2MyFrame1();
		void ShowScanList();

		void pme(const char* fmt, ...);
		void SetRow(aNetDevice a, int row);








};

#endif // __MyProject2MyFrame1__
