#ifndef __MyProject2MyFrame1__
#define __MyProject2MyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "MyProjectBase.h"

//// end generated include

#include "BG_ICMP.h"
#include <map>
#include <wx/msgdlg.h>


/** Implementing MyFrame1 */
class MyProject2MyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void m_BN_LoadHostListOnButtonClick( wxCommandEvent& event );
		void m_BN_RunOnceOnButtonClick( wxCommandEvent& event );
		void m_BN_RunPeriodicOnButtonClick( wxCommandEvent& event );
		void m_timer1OnTimer( wxTimerEvent& event );
		void m_comboBoxSitesOnCombobox(wxCommandEvent& event);
		virtual void m_menuItemAboutOnMenuSelection(wxCommandEvent& event)
		{
			char msg[] = "R&CS Pinger Developed by R&CS 5-6 in July 2025\r\nUsed to determine reachability of network devices on TDL WAN";
			wxMessageBox(msg,"About R&CS Pinger", wxOK );
		};
	public:
		/** Constructor */
		MyProject2MyFrame1( wxWindow* parent );
	//// end generated class members


		~MyProject2MyFrame1();
		void ShowScanList();

		void pme(const char* fmt, ...);
		void SetRow(aNetDevice a, int row);
		void BuildScanList(void);


		//https://learn.microsoft.com/en-us/windows/win32/api/ipexport/ns-ipexport-icmp_echo_reply
		std::map<int, std::string> ICMP_Status{ {0, "IP_SUCCESS"}, {11001, "IP_BUF_TOO_SMALL"}, {11002, "IP_DEST_NET_UNREACHABLE"} ,
		{11003, "IP_DEST_HOST_UNREACHABLE"} , {11004, "IP_DEST_PROT_UNREACHABLE"} , {11005, "IP_DEST_PORT_UNREACHABLE"} , {11006, "IP_NO_RESOURCES"} ,
		{11007, "IP_BAD_OPTION"} ,{11008, "IP_HW_ERROR"} ,{11009, "IP_PACKET_TOO_BIG"} ,{11010, "IP_REQ_TIMED_OUT"} ,{11011, "IP_BAD_REQ"} ,
		{11012, "IP_BAD_ROUTE"} , {11013, "IP_TTL_EXPIRED_TRANSIT"} , {11014, "IP_TTL_EXPIRED_REASSEM"} , {11015, "IP_PARAM_PROBLEM"} , {11016, "IP_SOURCE_QUENCH"} ,
		{11017, "IP_OPTION_TOO_BIG"} , {11018, "IP_BAD_DESTINATION"} , {11018, "IP_GENERAL_FAILURE"}  };



};

#endif // __MyProject2MyFrame1__
